kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

workspace:
  base: /go
  path: src/github.com/c-mueller/ads

steps:
  - name: load-deps
    image: golang
    commands:
      - go get -d ./...
      - go get github.com/Flaque/filet
      - go get github.com/stretchr/testify/assert
  - name: build-coredns-amd64
    image: golang
    commands:
      - cd /go/src/github.com/coredns/coredns
      # Uncomment once Two param TestCase Method is in release
      # probably v1.4.0
      - git checkout $(git describe --tags --abbrev=0)
      - sed -i 's|hosts:hosts|ads:github.com/c-mueller/ads\nhosts:hosts|g' plugin.cfg
      - cat plugin.cfg
      - make
      - mkdir /go/src/github.com/c-mueller/ads/binaries
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-amd64
  - name: test
    image: golang
    commands:
      - go test -v ./...
  - name: build-coredns-arm
    image: golang
    environment:
      GOOS: linux
      GOARCH: arm
    commands:
      - cd /go/src/github.com/coredns/coredns
      - make
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-arm
  - name: build-coredns-arm64
    image: golang
    environment:
      GOOS: linux
      GOARCH: arm
    commands:
      - cd /go/src/github.com/coredns/coredns
      - make
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-arm64
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: binaries/*
    when:
      event: tag

---
kind: signature
hmac: 33925d781f7d56eb0d2e18e56010c3ad052ce0d07d0b0a8ade999fbe7864356f